### ISSUE TITLE
12/4 full group meeting agenda

### ISSUE THREAD

**Issue by sparklingrobots** [drupaldiversity/contrib#17]
How do we manage the repo? 
Who gets admin rights? 
Can we split editing the wiki and merging pull requests? like trusted members (better name needed) only can merge? then 'everyone' could be a normal member without the ability to 'destroy' something
OpenDemographics project
CoC & Licensing questions

**Comment by sparklingrobots** [comment]
Cleverington: Would anyone be against choosing a specific workflow as a standard, such as using Pantheon's Terminus to build and/or Lando, etc. Just trying to think on how to create a 'solvent' workflow we can all use, which doesn't rely on simply writing up the instructions under the assumption of using something like Acquia Dev Desktop 2

**Comment by cleverington** [comment]
**Comment Edited for Readability**

For a little more clarification on the Workflow selection thoughts, Acquia Dev Desktop 2 is a great tool: yes, but starts to become limiting for late-scale development.

In contrast, something more complicated may create roadblocks for onboarding of new users.

Because of this, my recommendation for our workflows would be to choose one of the Docker-based environments we can 'customize' to our liking.  

## Local Development Environments

In no particular order here, just giving thoughts/feedback based on _personal_ experience.

Which would be why there's a lot of gaps. ;-)

Also did not include services with monthly Development charges.

| **Pro**                                                                                                       | **Con**                                                                                                       |
|---------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------|
| 1. Drupal VM                                                                                                  |                                                                                                               |
| URL: https://www.drupalvm.com/                                                                                |                                                                                                               |
| Works equally well on any OS (Windows Professional, OSX, Linux)                                               |                                                                                                               |
| Supports HEAVY customization, MultiSite, do-as-you-like configuration                                         | No 'at the ready' PaaS integrations, though this could be resolved via scripts                                |
| Once configuration is "done", we would only need to maintain a handful of easy to update files moving forward | Requires advanced user to setup initial configuration (and further users to *use* it)                         |
| Can be forked from main Repo to create                                                                        |                                                                                                               |
| Natively supports task runners for local testing/development. (SASS/SCSS, Compass, Grunt, Gulp, etc.)         |                                                                                                               |
| Supports CI workflows                                                                                         |                                                                                                               |
| 2. Lando                                                                                                      |                                                                                                               |
| URL: https://docs.devwithlando.io/tutorials/drupal8.html                                                      | ( The new version of Kalabox.io )                                                                             |
| Works equally well on any OS (Windows Professional, OSX, Linux)                                               |                                                                                                               |
| Lando / Pantheon / Behat Example already exists                                                               | Less customizable than Drupal-VM for 'End Users'                                                              |
| Works great with syncing directly to Pantheon Environments for Team-Development                               | Greater onboarding requirements for customization by Advanced Users                                           |
| Terminus, Composer, and other important PHP-development required tools already installed                      |                                                                                                               |
| Natively supports task runners for local testing/development. (SASS/SCSS, Compass, Grunt, Gulp, etc.)         |                                                                                                               |
| Supports CI workflows                                                                                         |                                                                                                               |
| 3. Acquia Dev Desktop 2                                                                                       |                                                                                                               |
| https://dev.acquia.com/downloads                                                                              |                                                                                                               |
| Works equally well on any OS (Windows Professional, OSX, Linux)                                               | Tends to quickly become limited for those who require more advanced Drush / Drupal Console Workflows          |
|                                                                                                               | Automation is limited                                                                                         |
|                                                                                                               | Does not natively support task runners for local testing/development. (SASS/SCSS, Compass, Grunt, Gulp, etc.) |
| 4. Amazee.io                                                                                                  |                                                                                                               |
| https://docs.amazee.io/                                                                                       |                                                                                                               |
| Not enough experience to give an educated evaluation.                                                         |                                                                                                               |
| 5. DockSal                                                                                                    |                                                                                                               |
| https://docksal.io/                                                                                           |                                                                                                               |
| Not enough experience to give an educated evaluation.                                                         |                                                                                                               |

**Comment by zenlan** [comment]
Strange that Drupal VM goes with Solr 4 when all the cool kids are using at least 6 if not 7.  I realise that this won't be an issue for most, just curious as to the reason. I tend to use Solr a lot and it takes seconds to set up 6/7 these days now that it no longer requires Tomcat/Jetty.

**Comment by sparklingrobots** [comment]
Two topics for the next meeting: 

1) How to publicize meeting times so everyone knows when the next meeting is AND can find that info for their own time zone 

2) How to easily find next steps for the team you are on

**Comment by sparklingrobots** [comment]
Using DDI Contrib Team organization
Add your mentors to your profile!!

**Comment by sparklingrobots** [comment]
Agenda: 

- Intros/Roll call 
- Add your mentors to your d.o profile! Add the DDI Contrib Team org to your profile!
- Moving to d.o: We will 
  -- DDI Contrib Project 
- DDI in Nashville: Who is coming? What do we want to do to promote our work?
  -- Free tickets for mentors, deadline 12/17 https://events.drupal.org/nashville2018/sign-be-mentor
- Global Sprint Weekend - 26-28 January
- Year-end Review
  -- Vision/Long-term goals (growing membership, diversifying membership)
  -- Project check-in (how are we feeling overall?)
- CoC & Licensing
- Personal check-in 
- Open floor
